/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as HandshakeRouteImport } from './routes/handshake'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxBitFlipperRouteImport } from './routes/sandbox/bit-flipper'
import { Route as HandshakeStep6RouteImport } from './routes/handshake.step-6'
import { Route as HandshakeStep5RouteImport } from './routes/handshake.step-5'
import { Route as HandshakeStep4RouteImport } from './routes/handshake.step-4'
import { Route as HandshakeStep3RouteImport } from './routes/handshake.step-3'
import { Route as HandshakeStep2RouteImport } from './routes/handshake.step-2'
import { Route as HandshakeStep1RouteImport } from './routes/handshake.step-1'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HandshakeRoute = HandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxBitFlipperRoute = SandboxBitFlipperRouteImport.update({
  id: '/bit-flipper',
  path: '/bit-flipper',
  getParentRoute: () => SandboxRoute,
} as any)
const HandshakeStep6Route = HandshakeStep6RouteImport.update({
  id: '/step-6',
  path: '/step-6',
  getParentRoute: () => HandshakeRoute,
} as any)
const HandshakeStep5Route = HandshakeStep5RouteImport.update({
  id: '/step-5',
  path: '/step-5',
  getParentRoute: () => HandshakeRoute,
} as any)
const HandshakeStep4Route = HandshakeStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => HandshakeRoute,
} as any)
const HandshakeStep3Route = HandshakeStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => HandshakeRoute,
} as any)
const HandshakeStep2Route = HandshakeStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => HandshakeRoute,
} as any)
const HandshakeStep1Route = HandshakeStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => HandshakeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handshake': typeof HandshakeRouteWithChildren
  '/sandbox': typeof SandboxRouteWithChildren
  '/handshake/step-1': typeof HandshakeStep1Route
  '/handshake/step-2': typeof HandshakeStep2Route
  '/handshake/step-3': typeof HandshakeStep3Route
  '/handshake/step-4': typeof HandshakeStep4Route
  '/handshake/step-5': typeof HandshakeStep5Route
  '/handshake/step-6': typeof HandshakeStep6Route
  '/sandbox/bit-flipper': typeof SandboxBitFlipperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handshake': typeof HandshakeRouteWithChildren
  '/sandbox': typeof SandboxRouteWithChildren
  '/handshake/step-1': typeof HandshakeStep1Route
  '/handshake/step-2': typeof HandshakeStep2Route
  '/handshake/step-3': typeof HandshakeStep3Route
  '/handshake/step-4': typeof HandshakeStep4Route
  '/handshake/step-5': typeof HandshakeStep5Route
  '/handshake/step-6': typeof HandshakeStep6Route
  '/sandbox/bit-flipper': typeof SandboxBitFlipperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handshake': typeof HandshakeRouteWithChildren
  '/sandbox': typeof SandboxRouteWithChildren
  '/handshake/step-1': typeof HandshakeStep1Route
  '/handshake/step-2': typeof HandshakeStep2Route
  '/handshake/step-3': typeof HandshakeStep3Route
  '/handshake/step-4': typeof HandshakeStep4Route
  '/handshake/step-5': typeof HandshakeStep5Route
  '/handshake/step-6': typeof HandshakeStep6Route
  '/sandbox/bit-flipper': typeof SandboxBitFlipperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/handshake'
    | '/sandbox'
    | '/handshake/step-1'
    | '/handshake/step-2'
    | '/handshake/step-3'
    | '/handshake/step-4'
    | '/handshake/step-5'
    | '/handshake/step-6'
    | '/sandbox/bit-flipper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handshake'
    | '/sandbox'
    | '/handshake/step-1'
    | '/handshake/step-2'
    | '/handshake/step-3'
    | '/handshake/step-4'
    | '/handshake/step-5'
    | '/handshake/step-6'
    | '/sandbox/bit-flipper'
  id:
    | '__root__'
    | '/'
    | '/handshake'
    | '/sandbox'
    | '/handshake/step-1'
    | '/handshake/step-2'
    | '/handshake/step-3'
    | '/handshake/step-4'
    | '/handshake/step-5'
    | '/handshake/step-6'
    | '/sandbox/bit-flipper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandshakeRoute: typeof HandshakeRouteWithChildren
  SandboxRoute: typeof SandboxRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handshake': {
      id: '/handshake'
      path: '/handshake'
      fullPath: '/handshake'
      preLoaderRoute: typeof HandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/bit-flipper': {
      id: '/sandbox/bit-flipper'
      path: '/bit-flipper'
      fullPath: '/sandbox/bit-flipper'
      preLoaderRoute: typeof SandboxBitFlipperRouteImport
      parentRoute: typeof SandboxRoute
    }
    '/handshake/step-6': {
      id: '/handshake/step-6'
      path: '/step-6'
      fullPath: '/handshake/step-6'
      preLoaderRoute: typeof HandshakeStep6RouteImport
      parentRoute: typeof HandshakeRoute
    }
    '/handshake/step-5': {
      id: '/handshake/step-5'
      path: '/step-5'
      fullPath: '/handshake/step-5'
      preLoaderRoute: typeof HandshakeStep5RouteImport
      parentRoute: typeof HandshakeRoute
    }
    '/handshake/step-4': {
      id: '/handshake/step-4'
      path: '/step-4'
      fullPath: '/handshake/step-4'
      preLoaderRoute: typeof HandshakeStep4RouteImport
      parentRoute: typeof HandshakeRoute
    }
    '/handshake/step-3': {
      id: '/handshake/step-3'
      path: '/step-3'
      fullPath: '/handshake/step-3'
      preLoaderRoute: typeof HandshakeStep3RouteImport
      parentRoute: typeof HandshakeRoute
    }
    '/handshake/step-2': {
      id: '/handshake/step-2'
      path: '/step-2'
      fullPath: '/handshake/step-2'
      preLoaderRoute: typeof HandshakeStep2RouteImport
      parentRoute: typeof HandshakeRoute
    }
    '/handshake/step-1': {
      id: '/handshake/step-1'
      path: '/step-1'
      fullPath: '/handshake/step-1'
      preLoaderRoute: typeof HandshakeStep1RouteImport
      parentRoute: typeof HandshakeRoute
    }
  }
}

interface HandshakeRouteChildren {
  HandshakeStep1Route: typeof HandshakeStep1Route
  HandshakeStep2Route: typeof HandshakeStep2Route
  HandshakeStep3Route: typeof HandshakeStep3Route
  HandshakeStep4Route: typeof HandshakeStep4Route
  HandshakeStep5Route: typeof HandshakeStep5Route
  HandshakeStep6Route: typeof HandshakeStep6Route
}

const HandshakeRouteChildren: HandshakeRouteChildren = {
  HandshakeStep1Route: HandshakeStep1Route,
  HandshakeStep2Route: HandshakeStep2Route,
  HandshakeStep3Route: HandshakeStep3Route,
  HandshakeStep4Route: HandshakeStep4Route,
  HandshakeStep5Route: HandshakeStep5Route,
  HandshakeStep6Route: HandshakeStep6Route,
}

const HandshakeRouteWithChildren = HandshakeRoute._addFileChildren(
  HandshakeRouteChildren,
)

interface SandboxRouteChildren {
  SandboxBitFlipperRoute: typeof SandboxBitFlipperRoute
}

const SandboxRouteChildren: SandboxRouteChildren = {
  SandboxBitFlipperRoute: SandboxBitFlipperRoute,
}

const SandboxRouteWithChildren =
  SandboxRoute._addFileChildren(SandboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandshakeRoute: HandshakeRouteWithChildren,
  SandboxRoute: SandboxRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
